### ISSUE TITLE
Can spruce support complex replacement?

### ISSUE THREAD

**Issue by autumnw** [geofffranks/spruce#102]
Hi,

We have a yaml file likes the following, want to check with you if it works with spruce? We hope spruce can grab repositories.paas.path and repositories.paas.version correctly. 

name: Charlie
version: 42

repositories:
  - name: paas
    path: paas-app-artifacts
    version: "23"
  - name: iaas
    path: iaas-app-artifacts
    version: 42
  - artifact: "(( grab repositories.paas.path))/((grab repositories.paas.version))/meta.yml"

**Comment by geofffranks** [comment]
It looks like you want the concat operator for that:

`artifact: (( concat repositories.paas.path "/" repositories.paas.version "/meta.yml" ))`

Also, take a look at play.spruce.cf for playing around with example yaml files, and how spruce will handle them.

**Comment by jhunt** [comment]
I believe you want `(( concat ... ))` instead of the two grab calls in quotes:

```
repositories:
  - name: paas
    path: paas-app-artifacts
    version: "23"
  - name: iaas
    path: iaas-app-artifacts
    version: 42
  - artifact: (( concat repositories.paas.path "/" repositories.paas.version "/meta.yml" ))
```

see http://play.spruce.cf/#71c5a6be109e8d1a512a
