### ISSUE TITLE
[Bug] static_ips operator hangs with bad ranges

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#110]
If a `static` range ends before it starts, the static_ips operator loops for quite some time (if not infinitely).

This should be fixed.

Example:

```
networks:
- name: default
  subnets:
  - cloud_properties:
      random: stuff
    range: 10.244.10.0/24
    reserved: 10.244.10.5 - 10.244.10.254
    static: 10.244.10.2 - 10.244.1.3
```
