### ISSUE TITLE
static_ips not evaluated properly when using grabbed network name in instance_groups

### ISSUE THREAD

**Issue by JamesClonk** [geofffranks/spruce#122]
It seems spruce does not evaluate `(( static_ips ))` before doing a `(( grab ))` when using `instance_groups`. I end up with "(( static_ips ))" strings in my templates.

See http://play.spruce.cf/#a7fdc048b854b96c1051f5817b44967a

```
--- # jobs.yml
instance_groups:
- name: example
  instances: 3
  networks:
  - name: (( grab properties.network_name ))
    static_ips: (( static_ips(0,1,2) ))

--- # properties.yml
properties:
  network_name: net1
  api_servers: (( grab instance_groups.example.networks.net1.static_ips ))

--- # networks.yml
networks:
- name: net1
  subnets:
  - cloud_properties: random
    static:
    - 192.168.0.2 - 192.168.0.10
```

produces this output:

```
properties: 
  api_servers: (( static_ips(0,1,2) ))
```

It works though when specifying via array element/index 0:

```
--- # properties.yml
properties:
  network_name: net1
  api_servers: (( grab instance_groups.example.networks.[0].static_ips ))
```

tested with spruce 1.4.0.
