### ISSUE TITLE
Support for wildcards/regexps for grab

### ISSUE THREAD

**Issue by mtekel** [geofffranks/spruce#125]
To be able to grab multiple items that are the same, e.g. azs.*.name in http://play.spruce.cf/#1b850fa29430383c1175c681953123a4 instead of having to specify azs.0.name azs.1.name and azs.2.name...

**Comment by saliceti** [comment]
+1
This would be really useful.

**Comment by jhunt** [comment]
If we handle this at the parameter-level as a form of macro-processing, it works without needing to introduce extra logic to all the operators.

This:

```
meta:
  first: 1
  second: 2
  third: 3

output: (( grab meta.* ))
list: (( join "-", meta.*, "4" ))
```

is transformed into:

```
meta:
  first: 1
  second: 2
  third: 3

output: (( grab meta.first, meta.second, meta.third ))
list: (( join "-", meta.first, meta.second, meta.third, "4" ))
```

and would output:

```
meta:
  first: 1
  second: 2
  third: 3

output:
  - 1
  - 2
  - 3
list: "1-2-3-4"
```

**Comment by mtekel** [comment]
Yes, exactly this would be really great to have.

**Comment by jhunt** [comment]
Blargh.  The `ParseOpcall` routine (which turns things like `(( concat x y z ))` into a syntax tree of sorts) operates without reference to the YAML tree, allowing it to continue parsing all the operator calls even if one of them refers to a non-existent path in the tree.  We need to preserve this behavior at all costs.

We're probably going to have to introduce another pass over the operators, before dataflow graph construction but after operator parsing to expand out the globbed path references.

**Comment by jhunt** [comment]
On second though, that probably won't work because of the requisite dataflow dependencies introduced by globbed paths.  Consider:

```
meta:
  foo: yes
  bar: no

things: (( grab meta ))
stuff:  (( grab things.* ))
```

Pre-evaluation, `things.*` is an invalid path, but if there is a dataflow dependency of `$.stuff` -> `$.things`, it would work since `$.things` would resolve the grab to (effectively):

```
# meta omitted
things:
  foo: yes
  bar: no
stuff: (( grab things.* ))
```

which _does_ work.

Maybe we should treat this more like `(( inject ... ))` and do full-tree evaluation prior to the calling operator?
