### ISSUE TITLE
Operators never get executed under array + name edge case

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#130]
The example at a http://play.spruce.cf/#8977f4c2716717c569df3988a25eb5ce should produce output like this:

```
array:
- grab: grab bag!
  name: thing1
- grab: grab bag!
  name: thing2
- grab: grab bag! # currently this value isn't processed, and stays `(( grab meta.bag ))`
  name: thing2
```

Or alternatively, it should error, because there are two elements of the array named the same thing.
