### ISSUE TITLE
Add ability to add contents of another non-yml file

### ISSUE THREAD

**Issue by dennisjbell** [geofffranks/spruce#133]
Sometimes we need to add a large multiline block of text to a yaml file; for example, an nginx config file or script that would best be kept as a separate file.  That way, the file contents can be viewed and edited more naturally, or even be processed by content-specific tools: (validators, syntax highlighter, config file consumers)

Adding the ability to add the file contents inline would help this

```
---
meta:
  filename:  myfile.config

nginx:
  config: (( file meta.filename ))

some:
  other:
    file:
      contents: (( file "relative/path/to/file" ))
```
