### ISSUE TITLE
Prune operator creates side-effect with inject (and another edge case scenario)

### ISSUE THREAD

**Issue by HeavyWombat** [geofffranks/spruce#150]
During some tests with our Spruce based YAML generation, we realized that there are some cases where `(( prune ))` does not result in the desired structure. So far, we were able to produce three kind of scenarios for that:
- **Example 1**: `(( prune ))` in combination with `(( inject ))`
- **Example 2**: `(( prune ))` in a simple list
- **Example 3**: `(( prune ))` in a list entry, which will be a new list entry in the final list

Example 1 is actually our main pain point, because `(( inject ))` is very convenient for a lot of our use cases.

Example 3 is an edge case, since you do not need to prune, because it is a new entry anyway. However, if you choose to write it like that, the result will be strange and therefore I think it would be good to fix the behavior.

##### Example 1
```yml
---
meta:
  default:
    templates:
    - name: one
    - name: two
    update:
      canaries: 1
      max_in_flight: 3

jobs:
- name: main-job
  <<<: (( inject meta.default ))
  instances: 2
```
and
```yml
---
jobs:
- name: another-job
  <<<: (( inject meta.default ))
  instances: 1
  update:
    canaries: 2
    max_in_flight: (( prune ))
```
creates
```yml
jobs:
- instances: 2
  name: main-job
  templates:
  - name: one
  - name: two
  update:
    canaries: 1
- instances: 1
  name: another-job
  templates:
  - name: one
  - name: two
  update:
    canaries: 2
    max_in_flight: 3
```
Note that actually the prune occurs in the first entry, not the second one.

##### Example 2
```yml
---
meta:
  list:
  - one
  - two
  - three
```
and
```yml
---
meta:
  list:
  - one
  - (( prune ))
```
results in
```
1 error(s) detected:
 - $.meta.list.1: (( prune )) operator not defined
```
As far as I read it, this is because prune is not supported for list entries at the moment.

##### Example 3
```yml
---
list:
- name: A
  release: A
  version: A

- name: B
  release: B
  version: B

- name: C
  release: C
  version: C
```
and
```yml
---
list:
- name: D
  release: D
  version: (( prune ))
```
creates
```yml
list:
- name: A
  release: A
- name: B
  release: B
  version: B
- name: C
  release: C
  version: C
- name: D
  release: D
```
Note that `name: A` and `name: D` are pruned.

I think the main reason behind this is caused by the point in time at which the path for the later prune is saved. I played around and I think I have an idea of a fix. I would like to double check it tomorrow and eventually create a pull request if I feel more confident.
