### ISSUE TITLE
Using concat with static_ip's

### ISSUE THREAD

**Issue by fearoffish** [geofffranks/spruce#156]
The following syntax would be useful, so we can use network ranges at a site level.
```
---
meta:
  network_prefix: "10.4"

networks:
- name: cf1
  subnets:
  - range: 10.4.36.0/24
    static: [ (( concat meta.network_prefix ".5.4 - " meta.network_prefix ".5.100" )) ]

jobs:
- name: pepe
  instances: 1
  networks:
  - name: cf1
    static_ips: (( static_ips(0) ))
```
