### ISSUE TITLE
Merge estrategy changes to `inline` if one of the arrays gets elements with `grab`

### ISSUE THREAD

**Issue by keymon** [geofffranks/spruce#171]
# Summary

In the documentation it says:

> If you don't specify a specific merge strategy, the array will be merged automatically; using keys if they exist (i.e. `(( merge ))`, and array indices otherwise (`(( inline ))`).

When merging  arrays where one of the arrays fetches the elements  `(( grab ... ))`, the strategy is changed to `inline`. 

## Example case

Given the following test case (http://play.spruce.cf/#aa7aff99e8e5cb064019707d559c92e7)

```yaml
--- # base.yml
list:
  - (( grab meta.list.a ))
  - (( grab meta.list.b ))

--- # a.yml 
meta:
  list:
    - name: a
      val: 1

--- # b.yml 
meta: 
  list:
    - name: b
      val: 2

--- # c.yml 
list:
  - name: c
    val: 3
```

Currently we get:

```yaml
list:
- name: c
  val: 3
- name: b
  val: 2
```

That is equivalent to specify `((inline))` in `c.yml`

## Expected result

I would expect spruce to detect that this is still a case of a key (`name`) base merge, and produce  this output:

```yaml
list:
- name: a
  val: 1
- name: b
  val: 2
- name: c
  val: 3
```

### Option one, add `((append))` to `c.yml`:

The workaround is add a `((append))` strategy in `c.yml`, to append the elements to the list

### Option two, use `((inline))` in the base.yml

This way we keep the keys `name` in the list to merge. http://play.spruce.cf/#9eace434bb2b4630df642b70480851f7

``` 
--- # base.yml
list:
  - name: a
    data: (( inject meta.list.a ))
  - name: b
    data: (( inject meta.list.b ))
 
--- # a.yml 
meta:
  list:
    - name: a
      val: 1

--- # b.yml 
meta: 
  list:
    - name: b
      val: 2

--- # c.yml 
list:
  - name: c
    val: 3
```

**Comment by keymon** [comment]
Note: I guess the workaround 2 is actually the right way to do this kind of merge. If you think this is not a bug, but the right way to do it, feel free to close this ticket, but I would update the documentation to explain this case.

**Comment by jhunt** [comment]
This is actually working as designed; we don't evaluate the `(( grab ... ))` operators until after we've merged all of the files, so the `(( inline ))` and `(( merge ))` directives don't see the thing behind the `(( grab ... ))`.  This strategy gives what we believe to be the most flexibility, at the expense of some esoteric use cases like grab-before-merge.

Without deferring `(( grab ... ))` (and other operators like concat, vault, etc.), the following is impossible:

```
--- # params.yml
meta:
  name: (( param "Please name the thing" ))
  
--- # global.yml
name: (( grab meta.name ))
properties:
  thing:
    name: (( grab meta.name ))
    url:  (( concat meta.name ".example.com" ))

--- # local.yml
meta:
  name: testing
```
(see http://play.spruce.cf/#77db47f5f02518983820f11f389c27fb)

Indeed, grab-before-merge causes a final structure that suffers from errors, because the `$.meta.name` `(( param ... ))` call is duplicated as `$.name` before it can be overridden in the final file.  This approaches the semantics of spiff, which we found to be burdensome and unintuitive.

Updating the documentation would be nice, but I believe it needs to go in its own section that describes the merge/eval phases as separate entites, as a sort of "deep dive" for people who are really trying to push the limits of what Spruce can do for them.
