### ISSUE TITLE
Default return value when redacting vault?

### ISSUE THREAD

**Issue by bodymindarts** [geofffranks/spruce#188]
We have the following:
```
meta:
  network_prefix: (( vault "secret/networking:network_prefix" ))

networks:
- name: bla
   subnets:
     static_ips: (( concat meta.network_prefix ".0.4 - " meta.network_prefix ".0.15" ))

jobs:
- name: bla
   networks:
   - name: bla
      static_ips: (( static_ips(0,1,2) ))
```

This works fine if vault is actually accessed but it doesn't when redacting because the `static_ip` operator doesn't know what to do with the ip range: `REDACTED.0.4 - REDACTED.0.15`.

Could we alter the vault operator to optionally return a default (redacted) value or skip redaction completely for individual values?
