### ISSUE TITLE
Unsupported type int64 error in calc operator

### ISSUE THREAD

**Issue by HeavyWombat** [geofffranks/spruce#190]
The `(( calc ... ))` operator generates an error even though it should technically be possible to use an `int64` value with the math expression. That is because one switch statement in the `calc` operator does not address all possible types correctly. I have a fix in mind and will create a pull request as soon as possible.

I was able to produce this issue by using a `(( grab key || <int> ))` construct.
```yaml
---
meta:
  foobar: (( grab meta.other-key || 0 ))

properties:
  foobar: (( calc "meta.foobar + 2" ))
```

The error message reads like this:
```
1 error(s) detected:
 - $.jobs.dea_next.instances: path meta.foobar is of type int64, which cannot be used in calculations
```
