### ISSUE TITLE
`--concourse` option working for `merge` but not for `json`

### ISSUE THREAD

**Issue by michaellihs** [geofffranks/spruce#193]
I have the following `yaml` file:

```yaml
---
meta:
  target: tutorial
  pipeline: learn-bosh-ci
  bosh-lite:
    target: 10.20.30.102
    username: admin
    password: admin
    deployment: learn-bosh

resources:
- name: git
  type: git
  source:
    uri: xxx
    private_key: {{private-repo-key}}

# ...
```

When I run `spruce --concourse merge pipeline.yml` everything works as expected. But when I run 

```spruce --concourse json pipeline.yml``` 

I get the following error:

```
pipeline.yml: unmarshal []byte to yaml failed: yaml: invalid map key: map[interface {}]interface {}{"private-repo-key":interface {}(nil)}
```
