### ISSUE TITLE
static_ips() dependency resolving broken with grab + vip networks

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#194]
VIP networks have no subnets/static IPs defined at the networking level. This is somehow breaking the dependency resolution for the static_ips operator.

This works:
```
meta:
  ips:
    - 1.2.3.4

networks:
- name: stuff
  subnets:
  - static: (( grab meta.ips ))

jobs:
- name: bosh
  instances: 1
  networks:
  - name: stuff
    static_ips: (( static_ips(0) ))

```

But this fails:
```
meta:
  ips:
    - 1.2.3.4

networks:
- name: stuff
  subnets:
  - static: (( grab meta.ips ))
- name: stuff2
  type: vip

jobs:
- name: bosh
  instances: 1
  networks:
  - name: stuff
    static_ips: (( static_ips(0) ))
```

With the following error:
```
$ spruce merge test.yml
1 error(s) detected:
 - $.jobs.bosh.networks.stuff.static_ips: $.networks.0.subnets.0.static.* is a scalar (not a map or a list)

```
