### ISSUE TITLE
`static_ips` should support plural `azs` in network definitions

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#201]
```
networks
- name: mynet
  subnets:
  - ... alll the usual stuff
    azs: [ z1, z2, z3 ]
```
is valid, but the operator currently only allows:
```
networks
- name: mynet
  subnets:
  - ... alll the usual stuff
    az: z1
```

We should fix this. Low priority, but in the mean time, adding the issue in case anyone else stumbles across this and needs a fix to `could not find AZ z2 (in network AZS [z1 z2 z3]`
