### ISSUE TITLE
Explode list of string into list of maps

### ISSUE THREAD

**Issue by william-tran** [geofffranks/spruce#212]
Given:
```
my-list:
- foo
- bar
- baz
```

Is there a way I can generate:

```
computed:
- name: foo
  path: /src/foo
- name: bar
  path: /src/bar
- name: baz
  path: /src/baz
```

From a template that doesn't need to know about the number of elements in my-list?

**Comment by geofffranks** [comment]
There currently is no operator to allow you to iterate over a list and run a data transformation on it. The closest we get is the cartesian-product operator, but that won't help for this case. 

Any suggestions on how you would want to define this in your yaml?

**Comment by william-tran** [comment]
Mapping a list of strings to a template
```
my-list:
- foo
- bar
- baz
```

And template

```
_templates:
  my-template:
    name: (( grab . ))
    path: (( concat "/src/" . ))

computed: (( map my-list my-template  ))
```
generates 
```
computed:
- name: foo
  path: /src/foo
- name: bar
  path: /src/bar
- name: baz
  path: /src/baz
```

Map a list of objects to a template:

```
my-list:
- key: foo
  value: bar
- key: fiz
  value: buz
```

And template

```
_templates:
  my-template:
    name: (( grab key ))
    path: (( concat "/src/" value ))

computed: (( map my-list my-template  ))
```
generates 
```
computed:
- name: foo
  path: /src/bar
- name: fiz
  path: /src/buz
```

We need a way to tell spruce not to evaluate `_templates` in the main context, only when evaluating `map`
