### ISSUE TITLE
((inject)) operator appends lists instead of overwriting them

### ISSUE THREAD

**Issue by cnelson** [geofffranks/spruce#213]
When using  `((inject))` to override a list property, the lists are merged instead of being overwritten.

Is this the expected behavior or a defect?

cc: @jmcarp

## How to reproduce 
```bash
spruce merge \
<(echo "---
foo:
  list:
  - old
  - list
") \
<(echo "---
bar:
  inject: (( inject foo ))
  list:
  - this should replace not append
")
```
**produces:** 
```yaml
bar:
  list:
  - old
  - list
  - this should replace not append
foo:
  list:
  - old
  - list
```

## Using (( replace )) doesn't help
```bash
spruce merge \
<(echo "---
foo:
  list:
  - old
  - list
") \
<(echo "---
bar:
  inject: (( inject foo ))
  list:
  - (( replace ))
  - using (( replace )) doesn't help
")
```
**produces:** 
```yaml
bar:
  list:
  - old
  - list
  - using (( replace )) doesn't help
foo:
  list:
  - old
  - list
```

## Using (( grab )) works for some reason
```bash
spruce merge \
<(echo "---
foo:
  list:
  - old
  - list
") \
<(echo "---
meta:
  list:
  - weirdly, this works

bar:
  inject: (( inject foo ))
  list: (( grab meta.list ))
")
```
**produces**
```yaml
bar:
  list:
  - weirdly, this works
foo:
  list:
  - old
  - list
meta:
  list:
  - weirdly, this works
```

**Comment by geofffranks** [comment]
The `(( replace ))`, `(( append ))`, and other array operators are evaluated as each YAML document is merged into the next, and `(( inject ))` is evaluated after all files have been merged into a single document, so the `(( append ))` and `(( replace ))` operators would have no affect there. As a result, I think we made the decision during implementation of `(( inject ))` to always append-merge arrays, right @jhunt ?

However, this seems to be counter-intuitive with the replace-by-default array merging behavior that spruce currently has, and could potentially make use of the new `--fallback-append` flag to control this behavior.  But given that this has worked this way for so long, I'm hesitant to flip the default behavior on people.

**Comment by cnelson** [comment]
I understand not wanting to change the default behavior but it's super unintuitive when lists are append but everything else gets overwritten.  Especially when the docs for inject say it's designed for overwriting:

 > but what if you want to inject data from a different file into your current map and then override some things?

If it helps at all out use case is we want to copy a bosh instance group and override the  VM extensions as seen here. https://github.com/18F/cg-deploy-concourse/blob/master/concourse-staging.yml#L31

Feel free to close this issue if this is the desired behavior.  I only wanted to make sure this wasn't an bug.

**Comment by jhunt** [comment]
I believe the original ask for `(( inject ... ))` was specifically to support templates, like this:

```
---
meta:
  jobs:
    consul: { just: [consul, things] }

jobs:
  consul_z1:
    .: (( inject meta.jobs.consul ))
    z2: specific
  consul_z2:
    .: (( inject meta.jobs.consul ))
    z2: specific
```

We `- (( append ))` all the constituent lists because otherwise it would be impossible to do something like this:

```
---
meta:
  PROTO:
    templates:
      - base
      - monitoring

servers:
  web:
    .: (( inject meta.PROTO ))
    templates:
      - http
      - https
      
  sftp:
    .: (( inject meta.PROTO ))
    templates:
      - ssh
```

and get the expected result:

```
servers:
  sftp:
    templates:
    - base
    - monitoring
    - ssh
  web:
    templates:
    - base
    - monitoring
    - http
    - https
```

(Thanks, http://play.spruce.cf/#548943f2a40e59328c260b30f134ba3f!)

I believe we specifically limit `(( inject ... ))` to a single argument, which means we could open up the call signature and append some flags to modify behavior.  Perhaps something like:

```
default:
  .: (( inject meta.template ))
replace:
  .: (( inject meta.template "replace" ))
prepend:
  .: (( inject meta.template "prepend" ))
append: # also the default
  .: (( inject meta.template "append" ))
```

Another option would be to introduce `(( inject-prepend ))`, `(( inject-append ))` and friends, which work like their analogs `(( prepend ))`, `(( append ))`, etc., but rather than belonging to merge-phase, belong to inject phase, and we finally reify `(( inject ... ))` as an secondary merge before eval -- it already is an ad hoc intermediary phase.

@geofffranks: thoughts?
