### ISSUE TITLE
Requesting support for array (( Merge on <map.key> ))

### ISSUE THREAD

**Issue by alewitt** [geofffranks/spruce#249]
Currently array merging accepts a key identifier, but only uses the the string provided and looks at the top level of the array map for the identifier. My use case has the `name` specified in a `metadata` section in every array element, and need help to do something like:
```
kind: List
items:
  - kind: Secret
    metadata:
      name: my-secrets-name
      annotations:
        version: dev
    data:
      data1: somedata
  - kind: ConfigMap
    metadata:
      name: my-configs-name
      annotations:
        version: dev
    data:
      data2: dataofsomesort
```
```
kind: List
items:
  - (( merge on metadata.name ))
  - kind: ConfigMap
    metadata:
      name: my-configs-name
      annotations:
        version: dev
    data:
      data2: alterData2
      data3: addData3
```

I dont have much control of the structure, so the name will always be under metadata.
