### ISSUE TITLE
The (( prune )) operator might remove the wrong element

### ISSUE THREAD

**Issue by HeavyWombat** [geofffranks/spruce#250]
We created a [example that should be as compact as possible in the Spruce playground](https://play.spruce.cf/#06832a74c691b5eaf823edfb702a9f41) to show why `(( prune ))` might be deleting the wrong part of the YAML. Basically, it happens if the order of a list is changed after the information about the prune path is stored.

```
--- # fileA.yml
list:
- name: one
  params:
    preload: true
    fail-fast: false

- name: two
  params:
    preload: true
    fail-fast: false

--- # fileB.yml
list:
- name: two
  params:
    preload: false
    fail-fast: (( prune ))

- (( prepend ))
- name: zero
  params:
    preload: true
    fail-fast: false
```

The expected outcome is that `fail-fast` of list entry named `two` is removed, however the `(( prepend ))` changes the order and therefore we end up removing an element in `one`.

We have a possible fix for this and will create a PR as soon the time permits. I would very much like your feedback on the proposed change to Spruce. Thanks in advance.
