### ISSUE TITLE
Question how to map dynamic ip in to manifest of neighbor job

### ISSUE THREAD

**Issue by Alexvianet** [geofffranks/spruce#257]
HI sorry for disturb, can someone help how to map(link) dynamic ip of neighbor job in to manifest.
I have fond hot to map static_ips: "(( jobs.postgres.networks.default.static_ips.[0] ))" but can't get how to map dynamic =(
also, a know how to map dynamic IP in templates but I need to do such in the manifest like:
Help please

```
    properties:
      alertmanager:
        receivers:
          - name: slack-receiver
            webhook_configs:
              - url: (( concat "http://" jobs.prom2teams.networks.dynamic.[0] ":8089/v2/Connector" ))
                send_resolved: true
```

![screenshot from 2018-04-16 11-38-13](https://user-images.githubusercontent.com/17483589/38801624-027f7308-4173-11e8-909e-be1b4e60ece2.png)

webhook_config:
url is not working =(

$.instance_groups.alertmanager.properties.alertmanager.receivers.slack-receiver.webhook_configs.0.url: Unable to resolve jobs.prom2teams.networks.dynamic.0: $.jobs could not be found in the datastructure
