### ISSUE TITLE
An ((import)) or ((load)) operator to load another file content before processing the current one

### ISSUE THREAD

**Issue by epcim** [geofffranks/spruce#262]
Obviously, this behavior was not needed up to now. Reasoning to add it to in my case is for an easier transition from other template processors. With current spruce, I cant from YAML file itself load a process another file, as I would do in another tool.

**Comment by epcim** [comment]
```
classes:
  - test1
  - test2
parameters:
  one:
    a: 1
    b: 2
```
kind of this class loading (example from reclass) I would like to simply convert to spurce.
