### ISSUE TITLE
BUG: Sequences are incorrectly merged

### ISSUE THREAD

**Issue by blissd** [geofffranks/spruce#264]
Given the following two yaml files:

a.yaml

```yaml
topics:
  - name: topic1
    partitions: 100
    replication: 2
    config:
      - name: cleanup.policy
        value: compact
  - name: topic2
    partitions: 100
    replication: 2
```

b.yaml

```yaml
topics:
  - name: topic3
    partitions: 100
    replication: 2
    config:
      - name: retention.ms
        value: 1000
```

Then merge with `spruce merge a.yaml b.yaml`.

The expected output is:

```yaml
topics:
  - name: topic1
    partitions: 100
    replication: 2
    config:
      - name: cleanup.policy
        value: compact
  - name: topic2
    partitions: 100
    replication: 2
  - name: topic3
    partitions: 100
    replication: 2
    config:
      - name: retention.ms
        value: 1000
```

However, the actual output is:

```yaml
topics:
- config:
  - name: cleanup.policy
    value: compact
  name: topic1
  partitions: 100
  replication: 2
- name: topic2
  partitions: 100
  replication: 2
- config:
  - name: retention.ms
    value: 1000
  name: topic3
  partitions: 100
  replication: 2
```

The `config` elements have been pulled up a level in the YAML heirarchy, thereby creating an output with elements at new levels than they were before. Also, some `name` elements under `topic` are no longer preceded by `-` so are no longer members of the sequence.
