### ISSUE TITLE
merge on other not working

### ISSUE THREAD

**Issue by lgfausak** [geofffranks/spruce#275]
This appears to be doing an inline merge.  I must be missing something obvious?

/tmp/doc1.yaml
```
test:
- (( merge on other ))
- other: 2
  doc1: array2
- other: 1
  doc1: array1

```
/tmp/doc2.yaml
```
test:
- other: 1
  doc2: array2
- doc2: array1
  other: 2
```
spruce merge /tmp/doc1.yaml /tmp/doc2.yaml
```
test:
- doc1: array2
  doc2: array2
  other: 1
- doc1: array1
  doc2: array1
  other: 2
```
Also (( merge on other )) is getting dropped.  It should be in the result, right?  I am thinking because an inline is being done instead of a merge on other, that is why it is dropped.

spruce merge --skip-eval /tmp/doc1.yaml /tmp/doc2.yaml
```
test:
- doc1: array2
  doc2: array2
  other: 1
- doc1: array1
  doc2: array1
  other: 2
```
I was expecting (( merge on other )) to remain in the result.
