### ISSUE TITLE
grab specific items from array to build a new array

### ISSUE THREAD

**Issue by giner** [geofffranks/spruce#277]
It would be very useful to be able to build a new array based on existent array. One of use-cases is managing internal ACLs based on network configuration.

For example
```
networks:
- name: net1
  subnets:
  - range: 10.10.11.0/24
    static:
    - 10.10.11.1 - 10.10.11.5
    - 10.10.11.11 - 10.10.11.15 
  - range: 10.10.12.0/24
    static:
    - 10.10.12.1 - 10.10.12.5
    - 10.10.12.11 - 10.10.12.15
```
grabbing:
```
ranges: (( grab networks.net1.[].range ))
static_ips:  (( grab networks.net1.[].static ))
```
result:
```
ranges:
- 10.10.11.0/24
- 10.10.12.0/24
static_ips:
- 10.10.11.1 - 10.10.11.5
- 10.10.11.11 - 10.10.11.15 
- 10.10.12.1 - 10.10.12.5
- 10.10.12.11 - 10.10.12.15
```
