### ISSUE TITLE
remove key when value of key is null or not exist

### ISSUE THREAD

**Issue by ghost** [geofffranks/spruce#290]
```--- # meta.yml
meta:
  test1: test1

--- # test.yml
clusters:
- name: mjolnir
  test1: (( grab meta.test1 || nil ))
  test2: (( grab meta.test2 || nil ))
```
command : `spruce merge --prune meta meta.yml test.yml`
result : 
```
clusters:
- name: mjolnir
  test1: test1
  test2: null
```

meta.test2 may exist or may not exist.
Can I remove test2 key in the result when test2 is null or meta.test2 does not exist?

I want to result as below
```
clusters:
- name: mjolnir
  test1: test1
```
