### ISSUE TITLE
Multiple Document Support?

### ISSUE THREAD

**Issue by mattdodge** [geofffranks/spruce#294]
Any current or planned support for multiple documents within YML? I'm not exactly sure how I'd expect this to work when merging (how would you know which document to merge with) but just curious if it's a known no-go. It's a common pattern I've seen to keep similar YML manifests together (k8s deployment and service, for example) so I think it's at least worth addressing.

Example (file.yml):
```yml
kind: Deployment
metadata:
  name: myapp
---
kind: Service
metadata:
  name: myapp-svc
```

```
$ spruce merge file.yml
kind: Deployment
metadata:
  name: myapp
```

**Comment by geofffranks** [comment]
So one source gets merged to a bunch of documents in a second file, but not more than one target file?

Eg spruce merge source.yml multi-doc.yml

But not spruce merge source.yml multi-doc-1.yml multi-doc-2.yml?

And source.yml is always a single doc?

**Comment by loksonarius** [comment]
Yeap, that's pretty much what first came to mind. It may not be the most logical or sane, but it just seemed intuitive and straightforward to implement.
Just providing that to start a discussion on what a possible multi-doc merge may look like -- just a proposal 😅 
Another approach that came to mind involved something like:

`spruce merge source.yaml multi-doc.yaml@2` doing `spruce merge source.yaml` against the second doc in `multi-doc.yaml`. Not sure how sensible this is, but it may be more straight forward. Still lets the user determine what's the exact merge logic they want. This would pair nicely with a `spruce collect/join/concat` command that combines all docs defined in input files into a single multi-doc.yaml file.

**Comment by geofffranks** [comment]
> On Aug 29, 2019, at 1:02 PM, Dan <notifications@github.com> wrote:
> 
> Yeap, that's pretty much what first came to mind. It may not be the most logical or sane, but it just seemed intuitive and straightforward to implement.
> Just providing that to start a discussion on what a possible multi-doc merge may look like -- just a proposal 😅
> Another approach that came to mind involved something like:
> 
> spruce merge source.yaml multi-doc.yaml@2 doing spruce merge source.yaml against the second doc in multi-doc.yaml. Not sure how sensible this is, but it may be more straight forward. Still lets the user determine what's the exact merge logic they want. This would pair nicely with a spruce collect/join/concat command that combines all docs defined in input files into a single multi-doc.yaml file.
> 
The @<file-index> is interesting and definitely more flexible, but I'd be worried it would get really annoying, if you want to just merge a specific set of settings into everything all the time (probably the most common use case). I'd be tempted to add a '@*' syntax to simplify. I think that would require some deeper changes to merging logic to support multiple simultaneous merges though.

merging a source onto one specific part of a multi-doc file but not the others doesn't seem very intuitive. Seems like you would be implying that part of the document should have spruce operators still, and part shouldn't. Does merging two different source files into different documents of a single multi-doc yaml seem like a common use case?

**Comment by loksonarius** [comment]
Not terribly, no. I'm honestly more in favor of the earlier approach I mentioned, but was providing the `@` one to discuss alternatives. In retrospect, I guess it's a pretty silly setup for the most part 😅.

**Comment by mattdodge** [comment]
@geofffranks brings up a good point about wanting to merge in settings to multiple docs, I can see that being a useful feature, and it's probably more aligned with my original use case when I brought this up.

I can also see wanting to merge into specific documents though. I'm a total spruce-noob but the more I think about this the more it seems similar to how array merging works. You need a way to identify documents just like you need a way to identify which object in a list to merge into. If we added an operator, similar to merge, called `(( document ))` or `(( document on name ))` you could target certain documents. I'm not exactly sure where you'd specify that operator though since we likely aren't working with a list at the top-level document. And up until now I haven't seen any "reserved" object keys that spruce relies on.

What if it was a command line arg to define how documents are identified? Example:
```bash
$ spruce merge --document-id=kind multi-doc.yml settings.yml more-doc.yml
```
**multi-doc.yml**
```yml
kind: Deployment
metadata:
  name: myapp
  label: (( grab settings.label ))
---
kind: Service
metadata:
  name: myapp-svc
  label: (( grab settings.label ))
```
**settings.yml**
```yml
settings:
  label: my-label
```
**more-doc.yml**
```yml
kind: Deployment
metadata:
  another: value
---
kind: Service
metadata:
  another: value-again
```

The merge would know you were targeting a document if you had the `kind` key at the top level document (based on the CLI arg), so merging together you'd get this:
```yml
kind: Deployment
metadata:
  name: myapp
  label: my-label
  another: value
---
kind: Service
metadata:
  name: myapp-svc
  label: my-label
  another: value-again
```

FWIW, for my original use case I just wanted to use the parse/eval feature of spruce on a multi-doc YML file, not actually do any merging. If there was a CLI command for `spruce eval` or something similar that only took one file and let me use some of the operators like `(( vault ))` and `(( grab $VAR ))` that would have been all I needed.

**Comment by geofffranks** [comment]
I put something together on the [multi-doc] branch, `spruce fan <source file> <target-multi-doc-1>...<multi-doc-N>`, where source is a single-doc file. It outputs a multi-doc stream of all the final merged data. Should support all of the same flags as `spruce merge`, just handles docs differently. Feel free to take it for a spin and offer up any feedback @loksonarius  @mattdodge ?

**Comment by mattdodge** [comment]
Awesome, thanks @geofffranks! I just gave it a spin and I think I see what you're going for here. It would let you "fan" a single settings-like file into a multi-doc file. 

The "merging" or handling of the series of multi-doc files isn't that intuitive to me though honestly. Specifying more than one multi-doc file appends all of the documents together. When I think of `spruce merge` I expect them all to get merged, not concatenated.

Specifically, if I use the example files I put in my previous comment and run this:
```
spruce fan --prune settings settings.yml multi-doc.yml more-doc.yml
```
I currently get this (4 documents in result set):
```yml
---
kind: Deployment
metadata:
  label: my-label
  name: myapp

---
kind: Service
metadata:
  label: my-label
  name: myapp-svc

---
kind: Deployment
metadata:
  another: value

---
kind: Service
metadata:
  another: value-again
```
I'd expect the two multi doc files to each get "merged" together though, so I would expect this:
```yml
kind: Deployment
metadata:
  name: myapp
  label: my-label
  another: value
---
kind: Service
metadata:
  name: myapp-svc
  label: my-label
  another: value-again
```
This is still super cool and exciting to see this coming together though! I think the idea to make it a separate command makes a lot of sense. Thanks again.
