### ISSUE TITLE
Add to array

### ISSUE THREAD

**Issue by arun-a-nayagam** [geofffranks/spruce#296]
Hi,

I want to add a value to an array, concat only deals with strings. Is there a different way to achieve the below behaviour

```
supported:
  methods:
     - GET
     - POST

api:
  methods: (( concat "OPTIONS" supported.methods))
```

<spruce merge>

Expected output:
```
api:
  methods:
    - OPTIONS
    - GET
    - POST
```
