### ISSUE TITLE
cannot reference path with key containing  '.'

### ISSUE THREAD

**Issue by thomasmitchell** [geofffranks/spruce#298]
```
---
stuff:
- name: beep.boop
  properties:
    thing: foo
    
want: (( grab stuff.beep.boop.properties.thing ))
```

results in:
```
1 error(s) detected:  - $.want: Unable to resolve `stuff.beep.boop.properties.thing`: `$.stuff.beep`
   → could not be found in the datastructure
```

`stuff.[beep.boop].properties.thing`
`stuff."beep.boop".properties.thing`
`stuff.beep\.boop.properties.thing`
these might be valid ways to escape such a path. Do you think that such an implementation would conflict greatly with existing templates?

**Comment by thomasmitchell** [comment]
It's also possible to attempt combining all combinations of dot-joined key names if a path cannot be found in the datastructure, which would provide a no-user-change-required way of doing this, but I'm not sure if that would have too large of a computation-time impact for such a niche edge-case.

**Comment by thomasmitchell** [comment]
This extends to hashes as well
```
---
stuff:
  beep.boop: foo
  
want: (( grab stuff.beep.boop ))
```

**Comment by thomasmitchell** [comment]
Existing workaround is to reference both from a pruned source that can be referenced, like:
```
---
meta:
  thing: foo
stuff:
  beep.boop: (( grab meta.thing ))
  
want: (( grab meta.thing ))
```
