### ISSUE TITLE
Right side of logical OR to be an array

### ISSUE THREAD

**Issue by arun-a-nayagam** [geofffranks/spruce#300]
Hi,

I am not sure if this is possible,

```
admin:
  protocols: [https, wss]

services:
  protocols: (( grab admin.protocols || "[https]" ))

spruce merge prune admin
services:
  protocols:
  - https
  - wss
```

When we grab admin.protocols, it rightly explodes it to an array whereas when admin.protocols is not present, the right side value is only interpreted as a string. 

Is there a way to interpret it as an array?

Thanks,
Arun
