### ISSUE TITLE
Merge inner arrays

### ISSUE THREAD

**Issue by arun-a-nayagam** [geofffranks/spruce#308]
Hi,

My play code is here,
https://play.spruce.cf/#e6e2c626f8cea81d2a2b2ee288596d31

I want the output to be like this, basically merge the inner arrays into one,
```
inference:
  plugins:
  - config:
      aud:
       - ap1
       - ap2
       - gp1
    name: connect
```
i.e config.aud formatted as an array as opposed to a list of inner arrays

Is this possible?

Thanks,
Arun
