### ISSUE TITLE
Array of maps

### ISSUE THREAD

**Issue by arun-a-nayagam** [geofffranks/spruce#309]
Hi,

Here's my use case,
https://play.spruce.cf/#030da6de5aeb2af1cd69838761b474ce

Is it possible for the output to be like this,

```
consumers:
- credentials:
  - key: ap1
  - key: ap2
  - key: gr1
  - key: gr2
```
