### ISSUE TITLE
Multiline reformatted during merge

### ISSUE THREAD

**Issue by stevewallone** [geofffranks/spruce#313]
During a merge, a multiline element is reformatted as a string with newline characters '\n'. Below is a snippet of the before and after. I'm wondering if there is a way to avoid this reformatting. 

```
 JCasC:
     enabled: true
     configScripts:
       base: |
         jenkins:
           agentProtocols:
             - "JNLP4-connect"
             - "Ping"

JCasC:
     configScripts:
       base: "jenkins:\n  agentProtocols:\n    - \"JNLP4-connect\"\n    - \"Ping\"
```
