### ISSUE TITLE
Cartesian product with a space

### ISSUE THREAD

**Issue by tamanna2702** [geofffranks/spruce#329]
I am trying the below as I need a space just after the colon:
```

---
meta:
  hosts:
    - a.example.com
    - b.example.com
    - c.example.com
  port: 8088

hosts: (( cartesian-product meta.hosts ":" " " meta.port ))
```

But Spruce seems to add single quotes to the results:

hosts:
- 'a.example.com: 8088'
- 'b.example.com: 8088'
- 'c.example.com: 8088'

Also, I tried the below :
```

---
meta:
  hosts:
    - a.example.com
    - b.example.com
    - c.example.com
  port: 8088

hosts: (( cartesian-product meta.hosts ": " meta.port ))
```

But I get the below error:

 file1.yml: unmarshal []byte to yaml failed: yaml: line 8: mapping values are not
             → allowed in this context
