### ISSUE TITLE
How to Join string and file contents together

### ISSUE THREAD

**Issue by omieee** [geofffranks/spruce#338]
Hi, I want to join the string and contents of a file together  and tried the following.

```
source: data:text//plain;base64,(( file "path-of-already-converted-base64-file" ))
```

The above doesn't work
whereas if I just remove the static string part it works

```
source: (( file "path-of-already-converted-base64-file" ))
```

How can I get the result in following format:

```
source: data:text/plain;base64,BASE_64_ENCODED_FILE_DATA_HERE
```

I am using ```spruce merge abc.yaml``` which contains the above code

**Comment by geofffranks** [comment]
Something like this should work:

```
data: (( file "path-to-file" ))
source: (( concat "data:text/plain;base64," data ))
```

**Comment by omieee-work** [comment]
Thank you, it worked. There is one more query i am trying to load two files in one file ex.

pre-deployment.yaml contents
```
apiVersion: v1
kind: List
metadata:
  name: name-here
  annotations:
    version: (( grab $TRAVIS_COMMIT || "dev" ))
items:
  (( file "file-path.yaml" ))
  (( file "file-path2.yaml" ))
```

After this I run ```spruce merge pre-deployment.yaml > output.yaml```

And i get following error

```
1 error(s) detected:
$.items: file operator requires exactly one string or reference argument
```
