### ISSUE TITLE
The result of merging depends on order data in a list

### ISSUE THREAD

**Issue by kazh000** [geofffranks/spruce#357]
When I merge follow two yaml files I get the expected result:
```
---
a:
- c: 1
  z:
  - x: 20
    "y": 25
- c: 2
  z:
  - x: 2
- [3, 4]
b: 30
---
a:
- c: 1
  z:
  - x: 20
    "y": 30
- c: 2
  z:
  - x: 3
```
The result:
```
a:
- c: 1
  z:
  - x: 20
    "y": 30
- c: 2
  z:
  - x: 3
- - 3
  - 4
b: 30
```
But when I change order in the first file I get  the unexpected result:
```
---
a:
- c: 1
  z:
  - x: 20
    "y": 25
- [3, 4]
- c: 2
  z:
  - x: 2
b: 30
---
a:
- c: 1
  z:
  - x: 20
    "y": 30
- c: 2
  z:
  - x: 3
```
The result:
```
a:
- c: 1
  z:
  - x: 20
    "y": 30
- c: 2
  z:
  - x: 3
- c: 2
  z:
  - x: 2
b: 30
```

**Comment by sorenisanerd** [comment]
With no explicit operator, spruce does an `(( inline ))` merge of arrays. You can read about it and its perils when dealing with arrays of maps here:

https://github.com/geofffranks/spruce/blob/master/doc/array-merging.md#operators-that-work-the-same-for-either-type-of-array

Briefly, `a` (an array) gets merged by merging each of its elements with the same (by index) element from the second document. This works fine for the first example, because the first element of `a` in the first doc is a map that merges well with the first element of `a` in the second doc. Same for the second element. Only one document has a third element in the `a` array, so the merging is straight forward.

In your second example, spruce actually attempts to merge `[3, 4]` with:

```yaml
- c: 2
  z:
  - x: 3
```
which, frankly, I'm not sure what should do.
