### ISSUE TITLE
Possible bug or advice needed

### ISSUE THREAD

**Issue by vulturm** [geofffranks/spruce#376]
Hello,

First of all thank you for this tool. I've integrated it in our workflow and I stumbled upon the following issue, possible yaml unmarshal bug.

* Spruce version: v1.30.2
* Description:
I would like to store a yaml file in AWS Secrets manager with plaintext option. Then use the `awssecret` DSL to fetch the content and be interpreted as yaml.

* Steps to reproduce:
Store the following yaml content in aws secrets manager:
```
options:
  labelsValidations:
    Owner:
    Manufacturer:
      - value1
      - value2
      - value3
      - value4
```
Then use the following file to retrieve it as a YAML structure:
```
cat qwe.yaml
---
fetched_from_secrets: (( awssecret "/sre/non-prod-config?key=options" ))
```

* Expected outcome:
```
# spruce merge qwe.yaml
fetched_from_secrets:
  labelsValidations:
    Owner:
    Manufacturer:
      - value1
      - value2
      - value3
      - value4
```

* Actual outcome:
```
spruce merge qwe.yaml
fetched_from_secrets: map[labelsValidations:map[Manufacturer:[value1 value2 value3
  value4] Owner:<nil>]]
```

I've tried various ways such as, not specifying the yaml key:
```
# cat qwe.yaml
---
fetched_from_secrets: (( awssecret "/sre/non-prod-config" ))

or

---
fetched_from_secrets:
  (( awssecret "/sre/non-prod-config" ))


# spruce merge qwe.yaml
fetched_from_secrets: |-
  options:
    labelsValidations:
      Owner:
      Manufacturer:
        - value1
        - value2
        - value3
        - value4
```
However, this way the value is presented as multiline string/block, and it can't be further parsed by subsequent `(( join "/" fetched_from_secrets.labelsValidations.Manufacturer ))` which we would like. 

Any suggestion that would allow me to achieve the `Expected outcome` ? 

Thank you in advance!
