### ISSUE TITLE
Grab a dynamic property from a map

### ISSUE THREAD

**Issue by SanderKnape** [geofffranks/spruce#383]
I'd like to grab a dynamic property from a map, something like this:

```
regions:
  foo: bar
  bar: baz
myregion: foo
result: (( grab regions[myregion] )) # should return "bar"
```

This doesn't work however. It does seem to work with environment variables: `result: (( grab regions.$MYREGION ))`, but I can't find out a way to reference another property instead.
