### ISSUE TITLE
Unable to concat int

### ISSUE THREAD

**Issue by rkoster** [geofffranks/spruce#44]
When merging the files below I get `interface conversion: interface is int, not string`

```yaml
releases:
- name: bosh
  url: file:///tmp/bosh-release.tgz
  version: 5
```

```yaml
releases:
- name: bosh
  url: (( concat "http://bosh.io/d/github.com/cloudfoundry/bosh?v=" releases.bosh.version ))
```
