### ISSUE TITLE
static_ips doesn't work when you merge static section of subnet from other place

### ISSUE THREAD

**Issue by allomov** [geofffranks/spruce#46]
Hey, everyone.

I have the following error. Here are template files:

* **jobs.yml**
```
jobs:
- name: api_z1
  instances: 3
  networks:
  - name: net1
    static_ips: (( static_ips(0, 1, 2) ))
```
* **networks.yml**
```
networks:
- name: net1
  subnets:
  - static: (( network_settings.static ))
```
* **settings.yml**
```
network_settings:
  static:
  - 10.10.2.65 - 10.10.2.70
```

When I run `spruce merge jobs.yml network.yml settings.yml` I've got the following error message:
```
1 error(s) detected:
 - $.jobs.api_z1.networks.net1.static_ips: `$.networks.net1.subnets.[0].static` is not an array
```

**Comment by geofffranks** [comment]
Yeah, this is a bug. I'm working on a complete overhaul to the postprocessor that will resolve this and other similar issues.

**Comment by geofffranks** [comment]
In the mean time, you can just have `settings.yml` override `networks.net1.subnets.[0].static` directly, rather than grabbing from network_settings, right?

**Comment by allomov** [comment]
Thank you for answer.

Yes, I can do it. But I wanted to have unified options, so I needed this feature.

Also there an idea of workaround by splitting rendering into two steps:
```
spruce merge network.yml settings.yml > intermediate-result.yml
spruce merge intermediate-result.yml jobs.yml 
```

Still the feature you working on will be very useful. Thank you.

**Comment by geofffranks** [comment]
Can you try building off of origin/master, and see if this issue is resolved for you? (and that no new ones were introduced)

**Comment by allomov** [comment]
I tried to run the merge command with the files I mentioned above, but still I got the an error:
```
$GOPATH/bin/spruce -v
/home/ubuntu/go/bin/spruce - Version 0.12.0 (master)
$
$ $GOPATH/bin/spruce merge jobs.yml network.yml settings.yml
1 error(s) detected:
 - $.jobs.0.networks.0.static_ips: $.networks.net1.subnets.*.static.* is a scalar (not a map or a list)
```

**Comment by filefrog** [comment]
Noticed a small bug in the original YAML files.

In `networks.yml`, you are trying to grab the value of `network_settings.static`, but using syntax that only works for spiff.  In spruce, all operators follow the pattern of `(( op arg1 arg2 ... argn ))`.

This works:

- jobs.yml
```yml
jobs:
- name: api_z1
  instances: 3
  networks:
  - name: net1
    static_ips: (( static_ips(0, 1, 2) ))
```

- networks.yml
```yml
networks:
- name: net1
  subnets:
  - static: (( grab network_settings.static ))       # note the "grab" operator
```

- settings.yml
```yml
network_settings:
  static:
  - 10.10.2.65 - 10.10.2.70
```

```
$ ./spruce -v
./spruce - Version 0.12.0 (0c3ae16)

$ ./spruce merge {jobs.networks,settings}.yml
jobs:
- instances: 3
  name: api_z1
  networks:
  - name: net1
    static_ips:
    - 10.10.2.65
    - 10.10.2.66
    - 10.10.2.67
network_settings:
  static:
  - 10.10.2.65 - 10.10.2.70
networks:
- name: net1
  subnets:
  - static:
    - 10.10.2.65 - 10.10.2.70
```

Amusingly enough, there actually was a bug lurking in released versions of spruce (0.12.0 included) whereby the `(( grab ... ))` inside of `$.networks.net1.subnets.0.static` wouldn't necessarily run before the `(( static_ips ... ))` call, leading to similar error messages about things being scalars and not lists.

So you'll still need to run this off of master until the next release.
