### ISSUE TITLE
Can not grab static_ips correctly

### ISSUE THREAD

**Issue by kei-yamazaki** [geofffranks/spruce#72]
The spruce can not grab static_ips correctoly in 99de7eb.

Following manifest can grab correctly.

```yaml
$ cat manifest.yml
networks:
  - name: test-network
    subnets:
      - static: [ 10.0.0.5 - 10.0.0.10 ]
jobs:
  - name: job1
    instances: 1
    networks:
      - name: test-network
        static_ips: (( static_ips(0) ))

z: (( grab jobs.job1.networks.test-network.static_ips ))
$ ./spruce merge manifest.yml
jobs:
- instances: 1
  name: job1
  networks:
  - name: test-network
    static_ips:
    - 10.0.0.5
networks:
- name: test-network
  subnets:
  - static:
    - 10.0.0.5 - 10.0.0.10
z:
- 10.0.0.5
```

But next manifest can not grab correctly.

```yaml
$ cat manifest.yml
networks:
  - name: test-network
    subnets:
      - static: [ 10.0.0.5 - 10.0.0.10 ]
jobs:
  - name: job1
    instances: 1
    networks:
      - name: test-network
        static_ips: (( static_ips(0) ))

a: (( grab jobs.job1.networks.test-network.static_ips ))
$ ./spruce merge manifest.yml
a: (( static_ips(0) ))
jobs:
- instances: 1
  name: job1
  networks:
  - name: test-network
    static_ips:
    - 10.0.0.5
networks:
- name: test-network
  subnets:
  - static:
    - 10.0.0.5 - 10.0.0.10
```

It seem to depend in order of key in yaml.

**Comment by filefrog** [comment]
This is a data flow problem related to name indirection, not specific to static_ips:

```
--- # manifest.yml
a:  (( grab b.squad.value ))
b:
  - name: squad
    value: (( grab c.value ))
c:
  value: VALUE
d: (( grab b.squad.value ))
e: (( grab c.value ))
```

gives the erroneous result:
```
a: (( grab c.value ))
b:
  - name: squad
    value: VALUE
c:
  value: VALUE
d: VALUE
e: VALUE
```

Data Flow analysis (`--trace` mode) shows the core problem:

```
...
-----> data flow: [0] wave 1, op a: (( grab b.squad.value ))
-----> data flow: [1] wave 1, op b.0.value: (( grab c.value ))
-----> data flow: [2] wave 1, op d: (( grab b.squad.value ))
-----> data flow: [3] wave 1, op e: (( grab c.value ))
...
```

`a` depends on `b.squad.value`, which doesn't technically exist in the YAML structure (as you can see in data flow slot [1], `b.0.value` is the canonical name.)

I'll work up a patch today or tomorrow and put the above YAML into the regression test suite.
