### ISSUE TITLE
Problem with exclamation marks in YML

### ISSUE THREAD

**Issue by jszroberto** [geofffranks/spruce#75]
Hi everyone, I was trying to use spruce  in the following way: 
```
bosh download manifest cf.yml 
spruce merge cf.yml mytemplate.yml 
```

And I found that spruce apparently has issues with ! , and the manifest deployed by Bosh contains them: 
```
properties: 
    route_registrar:
      routes:
      - name: uaa
        port: 8080
        tags:
          component: uaa
        uris:
        - uaa.fabric.ng.bluemix.net
        - ! '*.uaa.fabric.ng.bluemix.net'
```
The error that I get is: 
```
tmp/cf.yml: unmarshal []byte to yaml failed: yaml: line 525: did not find URI escaped octet

```

Any idea of what I could do? Thanks in advance

**Comment by filefrog** [comment]
I believe you are running into YAML tag syntax here.  See http://stackoverflow.com/questions/9664113/what-does-a-single-exclamation-mark-do-in-yaml

Try quoting the string value in its entirety:

```
properties: 
    route_registrar:
      routes:
      - name: uaa
        port: 8080
        tags:
          component: uaa
        uris:
        - uaa.fabric.ng.bluemix.net
        - "! '*.uaa.fabric.ng.bluemix.net'"
```
