### ISSUE TITLE
Inject not merging properly

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#77]
Inject is not merging arrays properly when injecting. It replaces rather than merges when that option is available. The yaml at http://play.spruce.cf/#bdeb1d30d979361217a5 should result in the below output, but does not (the `my_job` and `my_other_job` elements are missing from templates).

```
---
jobs:
  api_node:
    properties:
      foo: bar
      this: that
    templates:
    - name: my_job
      release: my_release
    - name: my_other_job
      release: my_other_release
    - name: my_superspecial_job
      release: my_superspecial_release
```
