### ISSUE TITLE
Concat with non-overridden param does not throw an error

### ISSUE THREAD

**Issue by geofffranks** [geofffranks/spruce#78]
For example:

http://play.spruce.cf/#a811a3dc3e2f70141779

**Comment by geofffranks** [comment]
This should throw an error for operators like concat, but for most other operators (grab, '||', inject), it should pull the 'param' value.

**Comment by filefrog** [comment]
I feel like http://play.spruce.cf/#07d972a67b9402c755b8 should complain about not setting `thing`, since that is where the `(( param ... ))` call is, not `value` which is just `grab`-ing it...

Thoughts?

**Comment by geofffranks** [comment]
The only downside to this is something like:
```
meta:
   base_domain: (( param "define this" ))
   system_domain: (( grab base_domain ))
```
If you're grabbing something that was in a param, and they're both in something you're pruning.. why are you grabbing it? I think I'm ok with this. 

I'd like to see how errors get displayed for something like this:
```
param: (( param "this is a param" ))
grab: (( grab param ))
concat: (( concat "is" param "?" ))
```
Both with and without `--prune param`? And how that compares to the current errors under those circumstances?

**Comment by filefrog** [comment]
The downside could be mitigated if we made `--prune` play a more prominent role in evaluation.  If we know that we are pruning `meta`, we can skip evaluation of any terminal sub-key of `meta` during DFA.

But that's an optimization for when we have a use case that warrants it.

Insofar as error messaging is concerned, given this YAML:

```
meta:
  domain: (( param "You must specify a system domain" ))
  unused: (( param "For some reason we thought we wanted this..." ))

system:
  base_domain: (( grab meta.domain ))
  app_domain: (( concat "apps." meta.domain ))
  url: (( concat "http://system." meta.domain ":8080/vhost/" meta.domain "/" ))
```

Should emit errors like this:
```
$.meta.domain: You must specify a system domain
$.meta.unused: For some reason we thought we wanted this...
```

That is to say:

  1. the double-reference from the `(( concat ... ))` doesn't result in double error messages
  2. place of assignment is called out as the erroring node

With a `--prune meta` in the mix, I would still expect the first error message:

```
$.meta.domain: You must specify a system domain
```

One might make the argument that the error is confusing because we are pruning meta, but the real point of `--prune` is to remove things from the _output_ YAML, not to ignore them completely...
