### ISSUE TITLE
Inject doesn't append to array

### ISSUE THREAD

**Issue by longnguyen11288** [geofffranks/spruce#84]
Inject doesn't append to array instead replace values 

File:
```
meta:
  jobs:
    consul:
      templates:
      - foo
      - bar
      foo: fun

jobs:
- name: consul
  templates:
  - qux
  inject: (( inject meta.jobs.consul ))
  quack: boo
```

Result:
```
jobs:
- foo: fun
  name: consul
  quack: boo
  templates:
  - qux
  - bar
meta:
  jobs:
    consul:
      foo: fun
      templates:
      - foo
      - bar
```

Desired Result:
```
jobs:
- foo: fun
  name: consul
  quack: boo
  templates:
  - foo
  - bar
  - qux
meta:
  jobs:
    consul:
      foo: fun
      templates:
      - foo
      - bar
```
